/* Tento zdrojový kód je pod licencí GNU/GPL. Můžete ho použít k vlastní
   potřebě, ale nesmíte jej ani programy založené na tomto kódu využít komerčně!

   Jedná se o zdrojový kód programu IQ Pokyd (http://iqpokyd.kyblsoft.cz)
   od Aleše Jandy
*/

/* IQ Pokyd - konstant.k - definice konstant programu
   Aleš Janda (C) KÝBLSoft 2002-2005 (kódování Windows 1250)
*/

#define FINALNI_VERZE 1 //! Musí být 1
#define VYDANI_VERZE_PROGRAMU "1"  //! Musí se změnit i v AboutBox

#define MAX_POCET_VSECH_SLOV 500000
#define MAX_DELKA_SLOVA 5000
#define MAX_DELKA_PODMINKY_A_ODPOVEDI 5000
#define MAX_DELKA_JMENA 50

#define POCET_PISMEN 28
#define POCET_DVOJPISMEN (POCET_PISMEN*POCET_PISMEN)
#define MAX_DELKA_ODPOVEDI_POCITACE 200

#define JMENO_ZAKLADNIHO_SLOVNIKU "SLOVNIK.IQP"
#define JMENO_UPLNEHO_SLOVNIKU "SLOVNIK.TMP"
#define JMENO_SOUBORU_S_INTELIGENCI "IQPOKYD.IQP"
#define JMENO_SOUBORU_S_PROFILEM "PROFIL.IQP"
#define JMENO_SOUBORU_S_NASTAVENIM "IQPOKYD.CFG"
#define JMENO_SOUBORU_S_NAPOVEDOU "CTI_ME.HTM"
#define JMENO_SOUBORU_S_TEXTOVYMI_ZAZNAMY "KYDY.TXT"
#define JMENO_SOUBORU_S_BINARNIMI_ZAZNAMY "NOVEINFO.IQP"

#define _pan_ 1
#define _hrad_ 2
#define _muz_ 3
#define _stroj_ 4
#define _predseda_ 5
#define _soudce_ 6
#define _zena_ 7
#define _ruze_ 8
#define _pisen_ 9
#define _kost_ 10
#define _mesto_ 11
#define _more_ 12
#define _kure_ 13
#define _staveni_ 14
#define _rony_ 15
#define _idea_ 16
#define _tema_ 17
#define _kalhoty_ 18
#define _data_ 19
#define _housle_ 20
#define _madam_ 21
#define _kupe_ 22

#define _mlady_ 31
#define _jarni_ 32
#define _matcin_ 33
#define _otcuv_ 34
#define _super_ 35

#define _osobni_ 41
#define _privlastnovaci_ 42
#define _ukazovaci_ 43
#define _tazaci_ 44
#define _vztazna_ 45
#define _neurcita_ 46
#define _zaporna_ 47

#define _je_ 60
#define _nese_ 61
#define _bere_ 62
#define _maze_ 63
#define _pece_ 64
#define _umre_ 65
#define _tiskne_ 66
#define _mine_ 67
#define _zacne_ 68
#define _kryje_ 69
#define _kupuje_ 70
#define _prosi_ 71
#define _trpi_ 72
#define _sazi_ 73
#define _dela_ 74

#define _mista_kde_ 81
#define _mista_kam_ 82
#define _casu_ 83
#define _zpusobu_ 84
#define _otazky_ 85

