/* IQ Pokyd - src/app/assets.ts - GENERATED by tools/extract-assets.mjs.
   Phase 6.2 of PLAN.md.  Do not edit it: run the extractor.

   Every image src/app/resources.ts lists, decoded out of the archive and
   re-encoded as a lossless PNG, with one Vite import each so that the build
   fingerprints and emits them.  The URLs are what phase 6.3 draws with; the
   sizes are the author's, in pixels, and are here because a menu bitmap that
   is 14x14 has to be told so before it is on the screen.

   The filenames are the archive's own, lowercased -- see the extractor's
   header for why, and for the one file whose case had to be folded.
*/

import img_kyblsoft from "./assets/kyblsoft.png";
import img_menukonec from "./assets/bitmap2.png";
import img_menunastaveni from "./assets/menunast.png";
import img_menumalanapoveda from "./assets/menumala.png";
import img_menuvelkanapoveda from "./assets/menuvelk.png";
import img_menuoprogramu from "./assets/menuopro.png";
import img_pozadimale from "./assets/pozmale.png";
import img_menuoverzi from "./assets/menuverz.png";
import img_menuinternet from "./assets/internet.png";
import img_kurzorklavesnice from "./assets/bmp00001.png";
import img_pozadihlavnihookna from "./assets/pozadi-iqpokyd.png";
import img_mainframe_32x32 from "./assets/iqpokyd-32x32.png";
import img_mainframe_16x16 from "./assets/iqpokyd-16x16.png";
import img_tvar_32x32 from "./assets/icon1-32x32.png";
import img_tvar_135x42 from "./assets/icon1-135x42.png";
import img_tvar16_32x32 from "./assets/ico00001-32x32.png";
import img_tvar16_16x16 from "./assets/ico00001-16x16.png";
import faviconUrl from "./assets/favicon.ico";

/** One picture out of the author's `res/` directory. */
export interface AssetImage {
  /** The author's symbol, spelled as src/app/resources.ts spells it. */
  id: string;
  /** The URL the bundler gave it.  Read it from here, never build it. */
  url: string;
  width: number;
  height: number;
  /** What the .rc called the file, backslash and original case and all. */
  source: string;
}

/** The bitmaps, keyed by the author's symbol. */
export const BITMAP_ASSETS: Record<string, AssetImage> = {
  IDB_KYBLSOFT: {
    id: "IDB_KYBLSOFT",
    url: img_kyblsoft,
    width: 132, height: 44,
    source: "res/kyblsoft.bmp",
  },
  IDB_MENUKONEC: {
    id: "IDB_MENUKONEC",
    url: img_menukonec,
    width: 14, height: 14,
    source: "res/bitmap2.bmp",
  },
  IDB_MENUNASTAVENI: {
    id: "IDB_MENUNASTAVENI",
    url: img_menunastaveni,
    width: 14, height: 14,
    source: "res/menunast.bmp",
  },
  IDB_MENUMALANAPOVEDA: {
    id: "IDB_MENUMALANAPOVEDA",
    url: img_menumalanapoveda,
    width: 14, height: 14,
    source: "res/menumala.bmp",
  },
  IDB_MENUVELKANAPOVEDA: {
    id: "IDB_MENUVELKANAPOVEDA",
    url: img_menuvelkanapoveda,
    width: 14, height: 14,
    source: "res/menuvelk.bmp",
  },
  IDB_MENUOPROGRAMU: {
    id: "IDB_MENUOPROGRAMU",
    url: img_menuoprogramu,
    width: 14, height: 14,
    source: "res/menuopro.bmp",
  },
  IDB_POZADIMALE: {
    id: "IDB_POZADIMALE",
    url: img_pozadimale,
    width: 100, height: 100,
    source: "res/POZMALE.BMP",
  },
  IDB_MENUOVERZI: {
    id: "IDB_MENUOVERZI",
    url: img_menuoverzi,
    width: 14, height: 14,
    source: "res/menuverz.bmp",
  },
  IDB_MENUINTERNET: {
    id: "IDB_MENUINTERNET",
    url: img_menuinternet,
    width: 14, height: 14,
    source: "res/internet.bmp",
  },
  IDB_KURZORKLAVESNICE: {
    id: "IDB_KURZORKLAVESNICE",
    url: img_kurzorklavesnice,
    width: 7, height: 28,
    source: "res/bmp00001.bmp",
  },
  IDB_POZADIHLAVNIHOOKNA: {
    id: "IDB_POZADIHLAVNIHOOKNA",
    url: img_pozadihlavnihookna,
    width: 900, height: 459,
    source: "res/pozadi-iqpokyd.bmp",
  },
};

/** The icons.  Each .ico in the archive holds more than one size, so each
 *  entry is a list, in the order the file's own directory gives them. */
export const ICON_ASSETS: Record<string, AssetImage[]> = {
  IDR_MAINFRAME: [
    {
      id: "IDR_MAINFRAME",
      url: img_mainframe_32x32,
      width: 32, height: 32,
      source: "res/IQPokyd.ico",
    },
    {
      id: "IDR_MAINFRAME",
      url: img_mainframe_16x16,
      width: 16, height: 16,
      source: "res/IQPokyd.ico",
    },
  ],
  IDI_TVAR: [
    {
      id: "IDI_TVAR",
      url: img_tvar_32x32,
      width: 32, height: 32,
      source: "res/icon1.ico",
    },
    {
      id: "IDI_TVAR",
      url: img_tvar_135x42,
      width: 135, height: 42,
      source: "res/icon1.ico",
    },
  ],
  IDI_TVAR16: [
    {
      id: "IDI_TVAR16",
      url: img_tvar16_32x32,
      width: 32, height: 32,
      source: "res/ico00001.ico",
    },
    {
      id: "IDI_TVAR16",
      url: img_tvar16_16x16,
      width: 16, height: 16,
      source: "res/ico00001.ico",
    },
  ],
};

/** `res/IQPokyd.ico`, copied out of the archive byte for byte.  index.html
 *  links it as the tab icon; nothing else should need it. */
export const FAVICON_URL: string = faviconUrl;
