#!/usr/bin/env python3
r"""Build the engine natively.

Phase 1.3 of PLAN.md: the first real compile.

What gets built
---------------
One translation unit for the engine -- `src/shim/engine.cpp`, which #includes
`vsechno.in` exactly as `!Prostre/IQPokyd.cpp` did, because vsechno.in is not a
header, it is the program -- plus the small `src/shim/` replacement for the
Win32/MFC surface, plus a driver if there is one.

The compiler is pointed at `build/cp1250/`, never at `src/engine/`.  This script
regenerates that tree first (tools/transcode.py --to-cp1250), so a build can
never be one edit stale.  See src/README.md.

The flags, and why each one
---------------------------
-std=gnu++98            The corpus predates C++11 and has 10 `"text "MACRO` string
                        concatenations that C++11 reads as user-defined literals
                        (hazard 8).  Also the closest thing to what MSVC 6 gave it.
-fsigned-char           Hazard 1.  The dictionary checksums, DEKODOVANY_ZNAK and
                        the mood delta all rely on `char` wrapping negative.  x86
                        gcc already defaults to signed; wasm clang does not, so the
                        flag is written down here rather than assumed.
-fwrapv                 Hazard 4: signed overflow is relied on, not avoided.
-fno-strict-aliasing    Hazard 4: 2005 C++, globals and casts everywhere.
-O1                     Hazard 4 again.  -O2 is not safe to reach for without
                        re-diffing the output, and there is nothing to diff against
                        until 1.6.
-DBEZ_PROSTREDI=1       Drops Aplikace/Prostred/, the MFC window.  It has to be 1
                        and not merely defined: Debug/DEBUG.FU:115 tests
                        `BEZ_PROSTREDI == 1`, and an empty macro makes that line a
                        preprocessor syntax error.
-Wall                   Kept on deliberately.  It is how hazard 4 gets an inventory:
                        7 -Wmaybe-uninitialized hits, one of them the
                        `nejlepsiodpoved` read PLAN.md predicted.  The surviving
                        warnings are catalogued in PLAN.md 1.3 -- read them, do not
                        silence them.
-Wno-write-strings      1588 hits of `char *p = "literal"`, the pre-ISO C++ idiom,
                        in code we are not going to change.
-Wno-misleading-indentation
                        57 hits, all of them the author's one-space indent style.
                        Formatting, not meaning.

IQPOKYDWINMFC is not set here.  engine.cpp defines it to 0, which is what selects
the author's own console paths (printf progress instead of SetWindowText, plain
fopen instead of GetModuleFileName).

Usage
-----
    python tools/build.py            # objects + link check (or the driver, if present)
    python tools/build.py -v         # show every command
"""

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHIM = ROOT / "src" / "shim"
DRIVER = ROOT / "src" / "driver"             # phase 1.5 lives here; absent until then
CP1250 = ROOT / "build" / "cp1250"
OUT = ROOT / "build" / "native"

CXX = "g++"

STD = ["-std=gnu++98"]
HAZARDS = ["-fsigned-char", "-fwrapv", "-fno-strict-aliasing", "-O1"]
DEFINES = ["-DBEZ_PROSTREDI=1"]
INCLUDES = ["-I", str(SHIM), "-I", str(CP1250)]
WARNINGS = ["-Wall", "-Wno-write-strings", "-Wno-misleading-indentation"]

CXXFLAGS = STD + HAZARDS + DEFINES + WARNINGS + INCLUDES

# A main() for when there is no driver yet.  Its only job is to make the linker
# resolve every reference in the engine object, which is the phase 1.3 gate.
LINKCHECK = r"""/* Generated by tools/build.py -- phase 1.3 link check, replaced by src/driver/. */
#include "engine.h"

int main(void) {
  printf("link check: engine linked.  Nastaveni %u B, answer buffer %u B, "
         "Struktura_vety %u B\n",
         (unsigned)sizeof(g_nastaveni), (unsigned)sizeof(g_odpovedpocitace),
         (unsigned)sizeof(g_vetacloveka));
  return 0;
 }
"""


def run(cmd, verbose):
    if verbose:
        print("  " + " ".join(str(c) for c in cmd))
    return subprocess.call([str(c) for c in cmd])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-v", "--verbose", action="store_true", help="show every command")
    args = ap.parse_args()

    # Never build stale bytes.
    if run([sys.executable, ROOT / "tools" / "transcode.py", "--to-cp1250"], args.verbose):
        return 1

    OUT.mkdir(parents=True, exist_ok=True)

    sources = sorted(SHIM.glob("*.cpp"))
    if DRIVER.is_dir():
        sources += sorted(DRIVER.glob("*.cpp"))
        entry = "driver"
    else:
        generated = OUT / "linkcheck.cpp"
        generated.write_text(LINKCHECK, encoding="ascii", newline="\n")
        sources.append(generated)
        entry = "link check"

    objects = []
    for src in sources:
        obj = OUT / (src.stem + ".o")
        print(f"compiling {src.relative_to(ROOT)}")
        if run([CXX] + CXXFLAGS + ["-c", src, "-o", obj], args.verbose):
            return 1
        objects.append(obj)

    exe = OUT / ("pokyd.exe" if sys.platform == "win32" else "pokyd")
    print(f"linking {exe.relative_to(ROOT)}  ({entry})")
    if run([CXX] + objects + ["-o", exe], args.verbose):
        return 1

    print(f"ok -> {exe}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
