//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IQPokyd.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MFC_DIALOG                  102
#define IDD_HLAVNI_OKNO                 102
#define IDR_MAINFRAME                   128
#define IDD_MODAL_NEMODAL               129
#define IDD_NACITANI                    130
#define IDR_MENU                        132
#define IDD_NASTAVENI                   133
#define IDD_HLAVNIOKNO                  134
#define IDR_ZKRATKY                     134
#define IDD_TEXT                        136
#define IDI_TVAR                        137
#define IDB_KYBLSOFT                    139
#define CREATEPROCESS_MANIFEST_RESOURCE_ID 144
#define IDD_DEBUGNASTAVENI              160
#define IDB_BITMAP1                     161
#define IDB_MENUKONEC                   162
#define IDB_MENUNASTAVENI               163
#define IDB_MENUMALANAPOVEDA            164
#define IDC_KURZOR                      164
#define IDB_MENUVELKANAPOVEDA           165
#define IDB_MENUOPROGRAMU               166
#define IDB_POZADIHLAVNIHOOKNA          168
#define IDB_POZADIMALE                  170
#define IDB_MENUOVERZI                  173
#define IDR_ZVUK_TUKNUTI                174
#define IDB_MENUINTERNET                176
#define IDI_TVAR16                      177
#define IDB_KURZORKLAVESNICE            179
#define IDC_MESSAGE_BOX                 1000
#define IDC_MODALNI                     1001
#define IDC_NEMODALNI                   1002
#define IDC_MOUSE_POS                   1006
#define IDC_CISLO                       1007
#define IDC_VETA                        1007
#define IDC_CISLA                       1008
#define IDC_ROZHOVOR                    1008
#define IDC_CISLO2CISLA                 1009
#define IDC_NOVAVETA                    1009
#define IDC_PROGRESNACITANI             1015
#define IDC_PROCENTA                    1023
#define IDC_TEXT                        1024
#define IDC_NADPIS                      1026
#define IDC_CLOVEKMUZ                   1027
#define IDC_CLOVEKZENA                  1028
#define IDC_POCITACZENA                 1029
#define IDC_POCITACMUZ                  1030
#define IDC_UKLADATROZHOVOR             1031
#define IDC_JMENOCLOVEKA                1032
#define IDC_JMENOPOCITACE               1033
#define IDC_ZABRAZOVATPOPISKY           1035
#define IDC_POUZIVATEFEKTY              1035
#define IDC_ZOBRAZOVATPOPISKY           1036
#define IDC_SPISOVNACESTINA             1037
#define IDC_POUZIVATZVUKY               1038
#define IDC_TEXT2                       1039
#define IDC_READONLYMOD                 1039
#define IDC_NADPIS2                     1040
#define IDC_NADPIS1                     1041
#define IDC_NADPIS3                     1042
#define IDC_CHARAKTER                   1055
#define IDC_NALADA                      1057
#define IDC_PODEKOVANI                  1059
#define IDC_HODNOTY                     1060
#define IDC_ZADNATOLERANCEPRAVOPISU     1061
#define IDC_EFEKTPROGRES1               1062
#define IDC_UPLNATOLERANCEPRAVOPISU     1062
#define IDC_EFEKTPROGRES2               1063
#define IDC_ZADNAREKURZEPROHLEDAVANI    1063
#define IDC_MALAREKURZEPROHLEDAVANI     1064
#define IDC_ODPOVEDPOCITACE1            1064
#define IDC_STREDNIREKURZEPROHLEDAVANI  1065
#define IDC_ODPOVEDPOCITACE2            1065
#define IDC_VELKAREKURZEPROHLEDAVANI    1066
#define IDC_ODPOVEDPOCITACE3            1066
#define IDC_MAXIMALNIREKURZEPROHLEDAVANI 1067
#define IDC_ODPOVEDPOCITACE4            1067
#define IDC_ODPOVEDPOCITACE5            1068
#define IDC_ODPOVEDPOCITACE6            1069
#define IDC_VETACLOVEKA6                1070
#define IDC_VETACLOVEKA5                1071
#define IDC_VETACLOVEKA4                1072
#define IDC_VETACLOVEKA3                1073
#define IDC_VETACLOVEKA2                1074
#define IDC_VETACLOVEKA1                1075
#define IDC_NALADABODY                  1076
#define IDC_CLOVEKPOHLAVI               1077
#define IDC_POCITACPOHLAVI              1078
#define IDC_JMENOCLOVEKASTATIC          1079
#define IDC_JMENOPOCITACESTATIC         1080
#define IDC_CHARAKTERSTATIC             1081
#define IDC_NALADASTATIC                1082
#define IDC_RYCHLEUKONCOVANI            1083
#define IDC_NAPISTVAVETA                1084
#define IDC_RAMECEK1                    1085
#define IDC_RAMECEK2                    1086
#define IDC_EMULOVATKLAVESNICI          1087
#define IDC_EMULOVATCESKOUKLAVESNICI    1088
#define IDC_EMULOVATSLOVENSKOUKLAVESNICI 1089
#define IDC_KLAVESNICEQWERTY            1090
#define IDC_TEXTKEMULACI                1091
#define IDC_NEZOBRAZOVATPOZADI          1092
#define IDC_ZOBRAZOVATSTANDARDNIKURZOR  1093
#define IDC_INTERNET                    1094
#define IDC_ZAKLADNINASTAVENI           1095
#define IDC_ROZSIRENENASTAVENI          1096
#define IDC_BUTTON                      1097
#define ID_NAPOVEDA                     32772
#define ID_OPROGRAMU                    32773
#define ID_KONEC                        32774
#define ID_NASTAVENI                    32775
#define ID_OVERZI                       32776
#define ID_ZKRATKA_SMAZRADEK            32778
#define ID_PREDCHOZIVETA                32779
#define ID_CHEAT_DEBUGINFO              32782
#define ID_VELKANAPOVEDA                32783
#define ID_MININAPOVEDA                 32784
#define ID_MALANAPOVEDA                 32785
#define ID_ZLEPSENINALADY               32787
#define ID_ZHORSENINALADY               32788
#define ID_ZLEPSENICHARAKTERU           32789
#define ID_ZHORSENICHARAKTERU           32790
#define ID_NAPOVEDA_INTERNET            32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
